name = "backend"
compatibility_date = "2024-07-16"

[vars]
DATABASE_URL ="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMWEzOWZkOTgtYmY3My00OTYzLWI0ZjUtOWRmMmE2ZTJkYjMxIiwidGVuYW50X2lkIjoiMTQwMzAwYjA4NWQ2NTFmYmQ1OWQwYzRlNTgyN2RlYjJmYmQyNmQxNTM5YWZkODhiYWViZjdhZDdjMGMwMjg5OCIsImludGVybmFsX3NlY3JldCI6ImRjMGRjZDg4LTcxZDgtNGUwYi05NzQ2LTgwNDAyMGQyZThjMyJ9.Ssx1IHQQxA4YRY2VRTZ3kHghwstNyC-LJn3keY0l2gE"
JWT_SECRET= "SAHILISTHEBESTANDYOUARETHELOSER"
